---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
  name: talos
spec:
  dataVolumeTemplates:
  - metadata:
      name: talos
    spec:
      source:
        http:
          url: https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.10.7/nocloud-amd64.raw.xz
      storage:
        resources:
          requests:
            storage: 5Gi
        storageClassName: replicated
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: u1.medium
  preference:
    kind: VirtualMachineClusterPreference
    name: ubuntu
  running: true
  template:
    metadata:
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: scsi
            name: systemdisk
          interfaces:
          - bridge: {}
            name: default
        firmware:
          uuid: 18068762-8f5d-40a8-933f-ad511392f556
        machine:
          type: ""
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - dataVolume:
          name: talos
        name: systemdisk
